cp

diff --git a/src/args/parse b/src/args/parse
--- a/src/args/parse
+++ b/src/args/parse
@@ -15,40 +15,39 @@ Summary
     Parse a command line.
 
 Description
-    Parse a command line by consuming a stream generated by 'cli args tokenize' 
-    concatenated with a stream of metadata generated by 'cli util serialize' 
-    consisting of the following variables:
+    Consume a stream of tokenized command line arguments and parsed help
+    metadata of the form:
 
-        CLI_META_REQUIRED
-        CLI_META_DEFAULT
-        CLI_META_IMPLICIT_VALUES
-        CLI_META_ALIASES
-        CLI_META_ALLOWED_VALUES 
-        CLI_META_POSITIONAL
+        struct {
+            args args
+            map_of meta meta
+        }
 
-    CLI_META_REQUIRED is an array of required options. For example, ( name ).
+        args {
+            map named
+            array positional
+        }
 
-    CLI_META_DEFAULT is an associative array of default values which are
-    assigned when the option is not present on the command line. All known
-    options must have a default. For example, ( [help]=false ).
+        meta {
+            map default
+            array require
+            map_of map allow
+            map alias
+            map implicit_value
+            boolean positional
+        }
 
-    CLI_META_IMPLICIT_VALUES is an associatie array of implicit values which
-    are assigned when the option is present on the command line but no value
-    is supplied or the value is the empty string. For example, ( [help]=true ).
+    See 'cli dsl meta' for 'meta' field definitions.
 
-    CLI_META_ALIASES is an assoicative array of aliases, typically a single 
-    letter. For example, ( [h]=help ). 
+    See 'cli args tokenize' for 'args' field definitions.
 
-    CLI_META_ALLOWED_VALUES is an associative array of space delimited allowed 
-    values for a given option. For example, ( [help]='true false' ). 
-
-    CLI_META_POSITIONAL is a boolean and specifies if positional arguments 
-    are accepted.
-
-Arguments
-    --result -r     : Array to store command name. Default: RESULT.
-    --options -o    : Associative array of optional arguments. Default: options.
-    --positional -p : Array of positional arguments. Default: positional.
+    'STRUCT_META' either has a single key '*' in which case there is only a single
+    valid set of 'meta' to be used to parse a command line, or it has many keys
+    each of which is a discriminating option name which determines the 'meta' to be
+    used to parse all remaining arguments. For example, many CLI accept two ways of
+    identifying a target resource: 'id' and 'name' + 'namespace'. In that case, 'id'
+    and 'name' could be used as discriminating options, and only when 'name' is
+    specified is 'namespace' allowed.
 
 Global Arguments
     --help -h        [Flag] : Show this message and exit.
@@ -56,218 +55,262 @@ Global Arguments
 
 Examples
     Parse 'grp cmd --option value -hg -- a0 a1'.
-        ${CLI_COMMAND} -- grp cmd --option value -hg -- a0 a1
+        cli args tokenize -- --header foo \
+        | ${CLI_COMMAND}
 EOF
 }
 
 inline() {
 
-    local -n ref_options=${arg_options}
-    local -n ref_positional=${arg_positional}
+    : ${arg_args:='ARGS'}
+    local -n POSITIONAL_ARGS=${arg_args}_POSITIONAL
+    local -n OPTIONAL_ARGS=${arg_args}_NAMED
 
-    local name
-    local alias
-    local value
+    : ${arg_meta:='META'}
+    
+    local group=0
+
+    local -n ALIAS=${arg_meta}_ALIAS
+    local -n DEFAULT=${arg_meta}_DEFAULT
+    local -n IMPLICT_VALUE=${arg_meta}_IMPLICIT_VALUE
+    local -n REQUIRE=${arg_meta}_REQUIRE
+    local -n ALLOW=${arg_meta}_ALLOW
+    local -n POSITIONAL=${arg_meta}_POSITIONAL
 
     # options
-    for option in "${!ref_options[@]}"; do
-        value="${ref_options[$option]}"
+    for option in "${!OPTIONAL_ARGS[@]}"; do
+        local value="${OPTIONAL_ARGS[$option]}"
+        local alias=${ALIAS[$option]-}
 
         # resolve aliases
-        alias=${CLI_META_ALIASES[$option]-}
         if [[ -n ${alias} ]]; then
-            unset 'ref_options[$option]'
+            unset 'OPTIONAL_ARGS[$option]'
             option=${alias}
-            ref_options[$option]="${value}"
+            OPTIONAL_ARGS[$option]="${value}"
         fi
 
         # trap for unknown arguments
-        if [[ -z ${CLI_META_DEFAULT[$option]+set} ]]; then
-            cli::fail "Unexpected unknown argument \"--${option}\"."
+        if [[ -z ${DEFAULT[$option]+set} ]]; then
+            cli::fail "Unexpected unknown argument '--${option}'."
         fi
 
         # trap for empty value and assign implicit value
-        if [[ -z "${value}" && -n ${CLI_META_IMPLICIT_VALUES[$option]+set} ]]; then
-            ref_options+=( [$option]="${CLI_META_IMPLICIT_VALUES[$option]}" )
+        if [[ -z "${value}" && -n ${IMPLICT_VALUE[$option]+set} ]]; then
+            OPTIONAL_ARGS+=( [$option]="${IMPLICT_VALUE[$option]}" )
         fi
     done
+    unset alias
+    unset value
 
     # default values
-    for option in ${!CLI_META_DEFAULT[@]}; do
-
+    for option in ${!DEFAULT[@]}; do
         # assign defaults to options not supplied on the command line
-        if [[ -z ${ref_options[$option]+set} ]]; then
-            ref_options+=( [$option]="${CLI_META_DEFAULT[$option]}" )
+        if [[ -z ${OPTIONAL_ARGS[$option]+set} ]]; then
+            OPTIONAL_ARGS+=( [$option]="${DEFAULT[$option]}" )
         fi
     done
 
     # required
-    for option in "${CLI_META_REQUIRED[@]}"; do
-        if [[ -z "${ref_options[$option]-}" ]]; then
-            cli::fail "Missing required argument \"--${option}\"."
+    for option in "${REQUIRE[@]}"; do
+        if [[ -z "${OPTIONAL_ARGS[$option]-}" ]]; then
+            cli::fail "Missing required argument '--${option}'."
         fi
     done
 
     # allowed values
-    for option in "${!CLI_META_ALLOWED_VALUES[@]}"; do
+    for option in "${!ALLOW[@]}"; do
 
-        # allowed values keys should have at least been assigned a default value
-        value=${ref_options[$option]?Unexpected bad allowed value metadata for \"${option}\".}
+        # args with restricted values must have been assigned an explicit or default value 
+        local value=${OPTIONAL_ARGS[$option]?Option \"${option}\" missing valid default value.}
 
-        # load allowed values into set
-        local -A allowed_values=()
-        arg_name=allowed_values ::cli::util::readset::inline \
-            < <(printf '%s\n' ${CLI_META_ALLOWED_VALUES[$option]})
+        # resolve name of set of allowed values
+        local -n allow=${arg_meta}_ALLOW_${ALLOW[${option}]}
 
         # test set for allowed value
-        if ! ${allowed_values[$value]-false}; then
-            cli::fail "Unexpected value '${value}' for argument \"--${option}\"."
+        if ! ${allow[$value]-false}; then
+            cli::fail "Unexpected value '${value}' for argument '--${option}'." \
+                "Expected a value in the set { "${!allow[@]}" }."
         fi
     done
+    unset value 
+    unset -n allow
 
     # positional
-    if ! ${CLI_META_POSITIONAL} && (( ${#ref_positional[@]} > 0 )); then
-        cli::fail "Unexpected positional argument(s)."
+    if ! ${POSITIONAL} && (( ${#POSITIONAL_ARGS[@]} > 0 )); then
+        cli::fail "Expected no positional arguments," \
+            "but got ${#POSITIONAL_ARGS[@]}: '${POSITIONAL_ARGS[@]}'."
     fi
 }
 
-main() {    
-    # declare tokens
-    local -a ${arg_result}
-    local -A ${arg_options}
-    local -a ${arg_positional}
+main() {
 
-    # declare metadata
-    local -A CLI_META_ALIASES
-    local -A CLI_META_DEFAULT
-    local -A CLI_META_ALLOWED_VALUES
-    local -a CLI_META_REQUIRED
-    local -A CLI_META_IMPLICIT_VALUES
-    local CLI_META_POSITIONAL
+    cli::define args
+    cli::define_field 'map' named args
+    cli::define_field 'array' positional args
 
-    # initialize tokens (i.e. command line lacks options or positional args)
-    local -n ref_options=${arg_options}
-    local -n ref_positional=${arg_positional}
-    ref_options=()
-    ref_positional=()
+    cli::define meta
+    cli::define_field 'map' default meta
+    cli::define_field 'array' require meta
+    cli::define_field 'map_of map' allow meta
+    cli::define_field 'map' alias meta
+    cli::define_field 'map' implicit_value meta
+    cli::define_field 'boolean' positional meta
 
-    # deserialize tokens and metadata
-    ::cli::util::deserialize::inline
+    cli::define
+    cli::define_field 'args' args
+    cli::define_field 'map_of meta' meta
 
-    inline "$@"
+    cli::declare
+    cli::read
 
-    ::cli::util::serialize::inline \
-        ${arg_result} \
-        ${arg_options} \
-        ${arg_positional}
+    arg_args=STRUCT_ARGS \
+    arg_meta=STRUCT_META_0 \
+        inline "$@"
+
+    cli::write STRUCT_ARGS args
 }
 
 self_test() {
-    local tokenize='cli args tokenize'
 
-    local -A CLI_META_DEFAULT=( [color]='black' )
-    local -A CLI_META_IMPLICIT_VALUES=()
-    local -a CLI_META_REQUIRED=( 'color' )
-    local -A CLI_META_ALIASES=( [c]='color' )
-    local -A CLI_META_ALLOWED_VALUES=( [color]='black white' )
-    local CLI_META_POSITIONAL=false
+    cat <(cli dsl sample -h \
+        | cli dsl tokenize \
+        | cli dsl parse \
+        | cli dsl meta \
+        | cli dsl bgen \
+        | sed s/^/meta\ /) \
+        <(cli args tokenize -- --f banana -h --header foo -- a0 a1 \
+        | sed s/^/args\ /) \
+    | cli args parse \
+    | sort \
+    | assert::pipe_records_eq \
+        'named display-args false' \
+        'named fruit banana' \
+        'named header foo' \
+        'named help true' \
+        'named id ' \
+        'named run-as ' \
+        'named self-test false' \
+        'positional a0' \
+        'positional a1'
 
-    meta() {
-        ::cli::util::serialize::inline \
-            CLI_META_REQUIRED \
-            CLI_META_IMPLICIT_VALUES \
-            CLI_META_DEFAULT \
-            CLI_META_ALIASES \
-            CLI_META_ALLOWED_VALUES \
-            CLI_META_POSITIONAL
+    args() {
+        cli args tokenize -- "$@" \
+            | sed s/^/'args '/
     }
 
-    # # default value (e.g. black)
-    cat <(meta) <(${tokenize}) \
-        | ${CLI_COMMAND} \
-        | assert::pipe_records_eq \
-        'options A color black'
+    test() {
+        local -a expected=()
+        while read; do expected+=( "${REPLY}" ); done
 
-    # # override default value (e.g. white)
-    cat <(meta) <(${tokenize} -- --color white) \
-        | ${CLI_COMMAND} \
-        | assert::pipe_records_eq \
-        'options A color white'
+        cat <(meta) <(args "$@") \
+            | ${CLI_COMMAND} \
+            | assert::pipe_records_eq \
+                "${expected[@]}"
+    }
 
-    # # override default value (e.g. white)
-    cat <(meta) <(${tokenize} -- --color green) \
-        | assert::fails "${CLI_COMMAND}"
+    test_fails() {
+        cat <(meta) <(args $1) \
+            | assert::fails "${CLI_COMMAND}" \
+                "${*:2}"
+    }
 
-    local -A CLI_META_DEFAULT=( [help]='false' )
-    local -A CLI_META_IMPLICIT_VALUES=( [help]='true' )
-    local -a CLI_META_REQUIRED=()
-    local -A CLI_META_ALIASES=( [h]='help' )
-    local -A CLI_META_ALLOWED_VALUES=( [help]='true false' )
-    local CLI_META_POSITIONAL=false
+    allow() {
+        meta() {
+            cat << EOF
+            meta * default color black
+            meta * require color
+            meta * alias c color
+            meta * allow color black
+            meta * allow color white
+EOF
+        }
 
-    # # add flag (e.g. help is 'false')
-    cat <(meta) <(${tokenize}) \
-        | ${CLI_COMMAND} \
-        | assert::pipe_records_eq \
-        'options A help false'
+        # default value (e.g. no --color)
+        test <<< 'named color black'
 
-    # set flag (e.g. '--help' -> help is 'true')
-    cat <(meta) <(${tokenize} -- --help) \
-        | ${CLI_COMMAND} \
-        | assert::pipe_records_eq \
-        'options A help true'
+        # override default value (e.g. --color white)
+        test --color white <<< 'named color white'
 
-    # set flag via alias (e.g. '-h' -> help is 'true')
-    cat <(meta) <(${tokenize} -- -h) \
-        | ${CLI_COMMAND} \
-        | assert::pipe_records_eq \
-        'options A help true'
+        # override default value with alias (e.g. -c white)
+        test -c white <<< 'named color white'
 
-    # flag is boolean (e.g. '--help maybe' disallowed)
-    cat <(meta) <(${tokenize} -- --help maybe) \
-        | assert::fails "${CLI_COMMAND}"
+        # set disallowed value
+        test_fails '--color green' \
+            "Unexpected value 'green' for argument '--color'." \
+            "Expected a value in the set { black white }."
+    }
 
-    local -A CLI_META_DEFAULT=( [name]='' )
-    local -A CLI_META_IMPLICIT_VALUES=()
-    local -a CLI_META_REQUIRED=( 'name' )
-    local -A CLI_META_ALIASES=()
-    local -A CLI_META_ALLOWED_VALUES=()
-    local CLI_META_POSITIONAL=false
+    flag() {
+        meta() {
+            cat << EOF
+            meta * default help false
+            meta * implicit_value help true
+            meta * alias h help
+            meta * allow help true
+            meta * allow help false
+EOF
+        }
 
-    # provide required options argument (e.g. '--name Bob')
-    cat <(meta) <(${tokenize} -- --name Bob) \
-        | ${CLI_COMMAND} \
-        | assert::pipe_records_eq \
-        'options A name Bob'
+        # add flag (e.g. help is 'false')
+        test <<< 'named help false'
 
-    # missing required options argument (e.g. missing '--name')
-    cat <(meta) <(${tokenize}) \
-        | assert::fails "${CLI_COMMAND}" 'missing requried'
+        # set flag (e.g. '--help' -> help is 'true')
+        test --help <<< 'named help true'
 
-    local -A CLI_META_DEFAULT=()
-    local -A CLI_META_IMPLICIT_VALUES=()
-    local -a CLI_META_REQUIRED=()
-    local -A CLI_META_ALIASES=()
-    local -A CLI_META_ALLOWED_VALUES=()
-    local CLI_META_POSITIONAL=true
+        # set flag with explicit value (e.g. '--help false' -> help is 'false')
+        test --help false <<< 'named help false'
 
-    # positional argument (e.g. '-- a0 a1')
-    cat <(meta) <(${tokenize} -- -- a0 a1) \
-        | ${CLI_COMMAND} \
-        | assert::pipe_records_eq \
-        'positional a a0' \
-        'positional a a1'
+        # set flag via alias (e.g. '-h' -> help is 'true')
+        test -h <<< 'named help true'
 
-    local -A CLI_META_DEFAULT=()
-    local -A CLI_META_IMPLICIT_VALUES=()
-    local -a CLI_META_REQUIRED=()
-    local -A CLI_META_ALIASES=()
-    local -A CLI_META_ALLOWED_VALUES=()
-    local CLI_META_POSITIONAL=false
+        # flag is boolean (e.g. '--help maybe' disallowed)
+        test_fails '--help maybe' \
+            "Unexpected value 'maybe' for argument '--help'." \
+            "Expected a value in the set { false true }."
+    }
 
-    # positional arguments disallowed (e.g. '-- a0')
-    cat <(meta) <(${tokenize} -- -- a0) \
-        | assert::fails "${CLI_COMMAND}" 'positional'
+    default() {
+        meta() {
+            cat << EOF
+            meta * default name
+            meta * require name
+EOF
+        }
+
+        # provide required named argument (e.g. '--name Bob')
+        test --name Bob <<< 'named name Bob'
+
+        # missing required named argument (e.g. missing '--name')
+        test_fails '' \
+            "Missing required argument '--name'."
+    }
+
+    positional() {
+        # positional argument allowed
+        cat <(echo 'meta * positional true') <(args -- a0 a1) \
+            | ${CLI_COMMAND} \
+            | assert::pipe_records_eq \
+            'positional a0' \
+            'positional a1'
+
+        # positional arguments disallowed (e.g. '-- a0')
+        cat <(echo 'meta * positional false') <(args -- a0) \
+            | assert::fails "${CLI_COMMAND}" \
+                "Expected no positional arguments, but got 1: 'a0'."
+    }
+
+    unknown() {
+        # no default values implies option is unknown (e.g. '--unknown')
+        cat <(echo 'meta * ') <(args --unknown) \
+            | assert::fails "${CLI_COMMAND}" \
+                "Unexpected unknown argument '--unknown'."
+    }
+
+    allow
+    flag
+    default
+    positional
+    unknown
 }
 
 cli::main "$@"
diff --git a/src/core/variable/put b/src/core/variable/put
--- a/src/core/variable/put
+++ b/src/core/variable/put
@@ -24,7 +24,7 @@ Arguments
     --                      : Record to put.
 
 Debug Arguments
-    --source -s      [Flag] : Source stdin to provide 'CLI_TYPE__*' metadata.
+    --source -s      [Flag] : Source stdin to provide 'CLI_TYPE_*' metadata.
 
 Global Arguments
     ${CLI_GLOBAL_ARG_HELP}
@@ -48,13 +48,17 @@ inline() {
 
         # scaler
         if arg_type=${arg_type} ::cli::core::type::is_scaler::inline; then
-            cli::check::condition "(( $# < 2 ))" "Unexpected excess value '${@:2}'."
+            cli::check::condition "(( $# < 2 ))"  \
+                "Failed to assign '${1-}' to ${arg_type} '${arg_name}'." \
+                "Expected a record with one or no fields, but got '$@'."
 
             # supplied
             if (( $# != 0 )); then
                 case ${type} in
-                    'boolean') cli::check::regex "$1" '^$|^true$|^false$' ;;
-                    'integer') cli::check::regex "$1" '^$|^[-]?[0-9]+$' ;;
+                    'boolean') cli::check::regex "${1-}" '^$|^true$|^false$' \
+                        "Failed to assign '${1-}' to ${arg_type} '${arg_name}'." ;;
+                    'integer') cli::check::regex "${1-}" '^$|^[-]?[0-9]+$' \
+                        "Failed to assign '${1-}' to ${arg_type} '${arg_name}'." ;;
                 esac
 
                 ref="$1" 
@@ -68,11 +72,14 @@ inline() {
 
         # map
         elif [[ ${type} == 'map' ]]; then
-            cli::check::condition "(( $# < 3 ))" "Unexpected excess value '${@:3}'."
+            cli::check::condition "(( $# < 3 ))" \
+                "Failed to assign value '${2:-}' to key '${1-}' in map '${arg_name}'." \
+                "Expected a record with two or fewer fields, but got '$@'."
 
             # supplied
             if (( $# != 0 )); then
-                cli::check::regex "${1-}" '.'
+                cli::check::regex "${1-}" '.' \
+                    "Failed to use empty key to assign '${2:-}' to map '${arg_name}'."
                 ref+=( [$1]="${2:-}" )
 
             # default
@@ -88,21 +95,21 @@ inline() {
             ref+=( "$@" ) 
         fi
 
-    else
+    elif (( $# > 0 )); then
         local next_type
         local next_name
 
         # anonymous
         if arg_type=${arg_type} ::cli::core::type::is_modified::inline; then
             next_type=${type[@]:1}
-            next_name=${arg_name}${CLI_NSS}${ref[$1]:-}
+            next_name=${arg_name}_${ref[$1]:-}
 
             if [[ ! -n ${ref[$1]+set} ]]; then
 
                 # update anonymous type
                 ref+=( [$1]=${#ref[@]} )
 
-                next_name=${arg_name}${CLI_NSS}${ref[$1]}
+                next_name=${arg_name}_${ref[$1]}
 
                 # declare variable
                 arg_name=${next_name} \
@@ -112,9 +119,14 @@ inline() {
 
         # user defined
         else
-            local -n fields_ref=CLI_TYPE__${type^^}
+            local -n fields_ref=CLI_TYPE_${type^^}
+
+            if [[ ! "${fields_ref[$1]+set}" == 'set' ]]; then
+                cli::fail "Field '$1' not found in '${type}' fields: { ${!fields_ref[@]} }."
+            fi
+
             next_type=${fields_ref[$1]}
-            next_name=${arg_name}${CLI_NSS}${1^^}
+            next_name=${arg_name}_${1^^}
         fi
 
         : ${next_name:?}
@@ -136,12 +148,12 @@ main() {
     arg_type="${arg_type}"
         inline "$@"
 
-    ::cli::bash::emit::inline 'CLI_TYPE__*' "${arg_name^^}" "${arg_name^^}_*"
+    ::cli::bash::emit::inline 'CLI_TYPE_*' "${arg_name^^}" "${arg_name^^}_*"
 }
 
 self_test() {
 
-    set_builtin() {
+    set_escaping() {
 
         # string
         declare MY_STRING=""
@@ -149,6 +161,30 @@ self_test() {
             | ${CLI_COMMAND} -s --name MY_STRING --type string -- 'Hello world!' \
             | assert::pipe_eq \
                 'declare -- MY_STRING="Hello world!"'
+
+        # array
+        declare -a MY_ARRAY
+        declare -p MY_ARRAY \
+            | ${CLI_COMMAND} -s --name MY_ARRAY --type array -- "a b c" \
+            | assert::pipe_eq \
+                'declare -a MY_ARRAY=([0]="a b c")'
+
+        # map
+        declare -A MY_MAP
+        declare -p MY_MAP \
+            | ${CLI_COMMAND} -s --name MY_MAP --type map -- a "b c" \
+            | assert::pipe_eq \
+                'declare -A MY_MAP=([a]="b c" )'
+    }
+
+    set_builtin() {
+
+        # string
+        declare MY_STRING=""
+        declare -p MY_STRING \
+            | ${CLI_COMMAND} -s --name MY_STRING --type string -- 'Hello' \
+            | assert::pipe_eq \
+                'declare -- MY_STRING="Hello"'
 
         # boolean
         declare MY_BOOLEAN=false
@@ -233,7 +269,7 @@ self_test() {
             | ${CLI_COMMAND} -s --name MY_MAP_OF_STRING --type 'map_of string' -- x 'Hello World' \
             | assert::pipe_eq \
                 "declare -A MY_MAP_OF_STRING=([x]=\"0\" )" \
-                "declare -- MY_MAP_OF_STRING__0=\"Hello World\""
+                "declare -- MY_MAP_OF_STRING_0=\"Hello World\""
 
         # boolean
         declare -A MY_MAP_OF_BOOLEAN=()
@@ -241,7 +277,7 @@ self_test() {
             | ${CLI_COMMAND} -s --name MY_MAP_OF_BOOLEAN --type 'map_of boolean' -- x true \
             | assert::pipe_eq \
                 "declare -A MY_MAP_OF_BOOLEAN=([x]=\"0\" )" \
-                "declare -- MY_MAP_OF_BOOLEAN__0=\"true\""
+                "declare -- MY_MAP_OF_BOOLEAN_0=\"true\""
 
         # integer
         declare -A MY_MAP_OF_INTEGER=()
@@ -249,7 +285,7 @@ self_test() {
             | ${CLI_COMMAND} -s --name MY_MAP_OF_INTEGER --type 'map_of integer' -- x 42 \
             | assert::pipe_eq \
                 "declare -A MY_MAP_OF_INTEGER=([x]=\"0\" )" \
-                "declare -i MY_MAP_OF_INTEGER__0=\"42\""
+                "declare -i MY_MAP_OF_INTEGER_0=\"42\""
 
         # array
         declare -A MY_MAP_OF_ARRAY=()
@@ -257,7 +293,7 @@ self_test() {
             | ${CLI_COMMAND} -s --name MY_MAP_OF_ARRAY --type 'map_of array' -- x a b c \
             | assert::pipe_eq \
                 "declare -A MY_MAP_OF_ARRAY=([x]=\"0\" )" \
-                "declare -a MY_MAP_OF_ARRAY__0=([0]=\"a\" [1]=\"b\" [2]=\"c\")"
+                "declare -a MY_MAP_OF_ARRAY_0=([0]=\"a\" [1]=\"b\" [2]=\"c\")"
 
         # map
         declare -A MY_MAP_OF_MAP=()
@@ -268,8 +304,8 @@ self_test() {
             | ${CLI_COMMAND} -s --name MY_MAP_OF_MAP --type 'map_of map' -- y a \
             | assert::pipe_eq \
                 'declare -A MY_MAP_OF_MAP=([y]="1" [x]="0" )' \
-                'declare -A MY_MAP_OF_MAP__0=([b]="1" [a]="0" )' \
-                "declare -A MY_MAP_OF_MAP__1=([a]=\"\" )"
+                'declare -A MY_MAP_OF_MAP_0=([b]="1" [a]="0" )' \
+                "declare -A MY_MAP_OF_MAP_1=([a]=\"\" )"
     }
 
     set_indirect_default() {
@@ -280,7 +316,7 @@ self_test() {
             | ${CLI_COMMAND} -s --name MY_MAP_OF_STRING --type 'map_of string' -- x \
             | assert::pipe_eq \
                 "declare -A MY_MAP_OF_STRING=([x]=\"0\" )" \
-                "declare -- MY_MAP_OF_STRING__0=\"\""
+                "declare -- MY_MAP_OF_STRING_0=\"\""
 
         # boolean
         declare -A MY_MAP_OF_BOOLEAN=()
@@ -288,7 +324,7 @@ self_test() {
             | ${CLI_COMMAND} -s --name MY_MAP_OF_BOOLEAN --type 'map_of boolean' -- x \
             | assert::pipe_eq \
                 "declare -A MY_MAP_OF_BOOLEAN=([x]=\"0\" )" \
-                "declare -- MY_MAP_OF_BOOLEAN__0=\"false\""
+                "declare -- MY_MAP_OF_BOOLEAN_0=\"false\""
 
         # integer
         declare -A MY_MAP_OF_INTEGER=()
@@ -296,7 +332,7 @@ self_test() {
             | ${CLI_COMMAND} -s --name MY_MAP_OF_INTEGER --type 'map_of integer' -- x \
             | assert::pipe_eq \
                 "declare -A MY_MAP_OF_INTEGER=([x]=\"0\" )" \
-                "declare -i MY_MAP_OF_INTEGER__0=\"0\""
+                "declare -i MY_MAP_OF_INTEGER_0=\"0\""
 
         # array
         declare -A MY_MAP_OF_ARRAY=()
@@ -304,7 +340,7 @@ self_test() {
             | ${CLI_COMMAND} -s --name MY_MAP_OF_ARRAY --type 'map_of array' -- x \
             | assert::pipe_eq \
                 "declare -A MY_MAP_OF_ARRAY=([x]=\"0\" )" \
-                "declare -a MY_MAP_OF_ARRAY__0=()"
+                "declare -a MY_MAP_OF_ARRAY_0=()"
 
         # map
         declare -A MY_MAP_OF_MAP=()
@@ -312,65 +348,107 @@ self_test() {
             | ${CLI_COMMAND} -s --name MY_MAP_OF_MAP --type 'map_of map' -- x \
             | assert::pipe_eq \
                 'declare -A MY_MAP_OF_MAP=([x]="0" )' \
-                'declare -A MY_MAP_OF_MAP__0=()'
+                'declare -A MY_MAP_OF_MAP_0=()'
     }
 
     set_udt() {
 
         # indirect
-        declare -A CLI_TYPE__VERSION=(['major']='integer' ['minor']='integer')
+        # declare -A CLI_TYPE_VERSION=(['major']='integer' ['minor']='integer')
+        # declare -A MY_MAP_OF_VERSION=()
+        # declare -p \
+        #     CLI_TYPE_VERSION \
+        #     MY_MAP_OF_VERSION \
+        #     | ${CLI_COMMAND} -s --name MY_MAP_OF_VERSION --type 'map_of version' -- x major 1 \
+        #     | ${CLI_COMMAND} -s --name MY_MAP_OF_VERSION --type 'map_of version' -- x minor 2 \
+        #     | assert::pipe_eq \
+        #         "declare -A CLI_TYPE_VERSION=([minor]=\"integer\" [major]=\"integer\" )" \
+        #         "declare -A MY_MAP_OF_VERSION=([x]=\"0\" )" \
+        #         "declare -i MY_MAP_OF_VERSION_0_MAJOR=\"1\"" \
+        #         "declare -i MY_MAP_OF_VERSION_0_MINOR=\"2\""
+
+        # indirect no key
+        declare -A CLI_TYPE_VERSION=(['major']='integer' ['minor']='integer')
         declare -A MY_MAP_OF_VERSION=()
         declare -p \
-            CLI_TYPE__VERSION \
+            CLI_TYPE_VERSION \
             MY_MAP_OF_VERSION \
-            | ${CLI_COMMAND} -s --name MY_MAP_OF_VERSION --type 'map_of version' -- x major 1 \
-            | ${CLI_COMMAND} -s --name MY_MAP_OF_VERSION --type 'map_of version' -- x minor 2 \
+            | ${CLI_COMMAND} -s --name MY_MAP_OF_VERSION --type 'map_of version' \
             | assert::pipe_eq \
-                "declare -A CLI_TYPE__VERSION=([minor]=\"integer\" [major]=\"integer\" )" \
+                "declare -A CLI_TYPE_VERSION=([minor]=\"integer\" [major]=\"integer\" )" \
+                "declare -A MY_MAP_OF_VERSION=()" \
+
+        # indirect key but no field
+        declare -A CLI_TYPE_VERSION=(['major']='integer' ['minor']='integer')
+        declare -A MY_MAP_OF_VERSION=()
+        declare -p \
+            CLI_TYPE_VERSION \
+            MY_MAP_OF_VERSION \
+            | ${CLI_COMMAND} -s --name MY_MAP_OF_VERSION --type 'map_of version' -- x \
+            | assert::pipe_eq \
+                "declare -A CLI_TYPE_VERSION=([minor]=\"integer\" [major]=\"integer\" )" \
                 "declare -A MY_MAP_OF_VERSION=([x]=\"0\" )" \
-                "declare -i MY_MAP_OF_VERSION__0__MAJOR=\"1\"" \
-                "declare -i MY_MAP_OF_VERSION__0__MINOR=\"2\""
+                "declare -i MY_MAP_OF_VERSION_0_MAJOR=\"0\"" \
+                "declare -i MY_MAP_OF_VERSION_0_MINOR=\"0\""
 
         # indirect default
-        declare -A CLI_TYPE__VERSION=(['major']='integer' ['minor']='integer')
+        declare -A CLI_TYPE_VERSION=(['major']='integer' ['minor']='integer')
         declare -A MY_MAP_OF_VERSION=()
         declare -p \
-            CLI_TYPE__VERSION \
+            CLI_TYPE_VERSION \
             MY_MAP_OF_VERSION \
             | ${CLI_COMMAND} -s --name MY_MAP_OF_VERSION --type 'map_of version' -- x major 1 \
             | ${CLI_COMMAND} -s --name MY_MAP_OF_VERSION --type 'map_of version' -- x major \
             | assert::pipe_eq \
-                "declare -A CLI_TYPE__VERSION=([minor]=\"integer\" [major]=\"integer\" )" \
+                "declare -A CLI_TYPE_VERSION=([minor]=\"integer\" [major]=\"integer\" )" \
                 "declare -A MY_MAP_OF_VERSION=([x]=\"0\" )" \
-                "declare -i MY_MAP_OF_VERSION__0__MAJOR=\"0\"" \
-                "declare -i MY_MAP_OF_VERSION__0__MINOR=\"0\""
+                "declare -i MY_MAP_OF_VERSION_0_MAJOR=\"0\"" \
+                "declare -i MY_MAP_OF_VERSION_0_MINOR=\"0\""
 
         # direct
-        declare -A CLI_TYPE__UDT=(['positional']='boolean' ['allow']='map_of map' ['version']='version')
-        declare -- MY_UDT__POSITIONAL=false
-        declare -i MY_UDT__VERSION__MAJOR=0
-        declare -i MY_UDT__VERSION__MINOR=0
-        declare -A MY_UDT__ALLOW=()
+        declare -A CLI_TYPE_UDT=(['positional']='boolean' ['allow']='map_of map' ['version']='version')
+        declare -- MY_UDT_POSITIONAL=false
+        declare -i MY_UDT_VERSION_MAJOR=0
+        declare -i MY_UDT_VERSION_MINOR=0
+        declare -A MY_UDT_ALLOW=()
         declare -p \
-            CLI_TYPE__UDT \
-            CLI_TYPE__VERSION \
-            MY_UDT__POSITIONAL \
-            MY_UDT__VERSION__MAJOR \
-            MY_UDT__VERSION__MINOR \
-            MY_UDT__ALLOW \
+            CLI_TYPE_UDT \
+            CLI_TYPE_VERSION \
+            MY_UDT_POSITIONAL \
+            MY_UDT_VERSION_MAJOR \
+            MY_UDT_VERSION_MINOR \
+            MY_UDT_ALLOW \
             | ${CLI_COMMAND} -s --name MY_UDT --type udt -- positional true \
             | ${CLI_COMMAND} -s --name MY_UDT --type udt -- version minor 2 \
             | ${CLI_COMMAND} -s --name MY_UDT --type udt -- version major 1 \
             | ${CLI_COMMAND} -s --name MY_UDT --type udt -- allow color white \
             | ${CLI_COMMAND} -s --name MY_UDT --type udt -- allow color black \
             | assert::pipe_eq \
-                'declare -A CLI_TYPE__UDT=([positional]="boolean" [version]="version" [allow]="map_of map" )' \
-                'declare -A CLI_TYPE__VERSION=([minor]="integer" [major]="integer" )' \
-                'declare -A MY_UDT__ALLOW=([color]="0" )' \
-                'declare -A MY_UDT__ALLOW__0=([black]="" [white]="" )' \
-                'declare -- MY_UDT__POSITIONAL="true"' \
-                'declare -i MY_UDT__VERSION__MAJOR="1"' \
-                'declare -i MY_UDT__VERSION__MINOR="2"'
+                'declare -A CLI_TYPE_UDT=([positional]="boolean" [version]="version" [allow]="map_of map" )' \
+                'declare -A CLI_TYPE_VERSION=([minor]="integer" [major]="integer" )' \
+                'declare -A MY_UDT_ALLOW=([color]="0" )' \
+                'declare -A MY_UDT_ALLOW_0=([black]="" [white]="" )' \
+                'declare -- MY_UDT_POSITIONAL="true"' \
+                'declare -i MY_UDT_VERSION_MAJOR="1"' \
+                'declare -i MY_UDT_VERSION_MINOR="2"'
+    }
+
+    test_missing_field() {
+
+        # indirect
+        set +e
+        declare -A CLI_TYPE_VERSION=(['major']='integer' ['minor']='integer')
+        declare -A MY_MAP_OF_VERSION=()
+        declare -p \
+            CLI_TYPE_VERSION \
+            MY_MAP_OF_VERSION \
+            | ${CLI_COMMAND} -s --name MY_MAP_OF_VERSION --type 'map_of version' -- x major 1 \
+            | ${CLI_COMMAND} -s --name MY_MAP_OF_VERSION --type 'map_of version' -- x minor 2 \
+            | ${CLI_COMMAND} -s --name MY_MAP_OF_VERSION --type 'map_of version' -- x missing 3 \
+              2>&1 >/dev/null \
+            | assert::error_message "Field 'missing' not found in 'version' fields: { minor major }."
+        assert::failed
+        set -e
     }
 
     test_bad_value() {
@@ -378,19 +456,25 @@ self_test() {
         declare MY_BOOLEAN
         declare -p MY_BOOLEAN \
             | ${CLI_COMMAND} -s --type boolean --name MY_BOOLEAN -- 'bad' \
-            2> /dev/null
+              2>&1 >/dev/null \
+            | assert::error_message "Failed to assign 'bad' to boolean 'MY_BOOLEAN'." \
+                "'bad' does not match regex '^$|^true$|^false$'."
         assert::failed
 
         declare -i MY_INTEGER
         declare -p MY_INTEGER \
             | ${CLI_COMMAND} -s --type integer --name MY_INTEGER -- 'bad' \
-            2> /dev/null
+              2>&1 >/dev/null \
+            | assert::error_message "Failed to assign 'bad' to integer 'MY_INTEGER'." \
+                "'bad' does not match regex '^$|^[-]?[0-9]+$'."
         assert::failed
 
         declare -A MY_MAP
         declare -p MY_MAP \
-            | ${CLI_COMMAND} -s --type map --name MY_MAP -- '' \
-            2> /dev/null
+            | ${CLI_COMMAND} -s --type map --name MY_MAP -- '' 'val' \
+              2>&1 >/dev/null \
+            | assert::error_message "Failed to use empty key to assign 'val' to map 'MY_MAP'." \
+                "'' does not match regex '.'."
         assert::failed
         set -e
     }
@@ -400,27 +484,33 @@ self_test() {
         declare MY_BOOLEAN
         declare -p MY_BOOLEAN \
             | ${CLI_COMMAND} -s --type boolean --name MY_BOOLEAN -- 'true' 'bad' \
-            2> /dev/null
+              2>&1 >/dev/null \
+            | assert::error_message "Failed to assign 'true' to boolean 'MY_BOOLEAN'." \
+                "Expected a record with one or no fields, but got 'true bad'."
         assert::failed
 
         declare -A MY_MAP
         declare -p MY_MAP \
             | ${CLI_COMMAND} -s --type map --name MY_MAP -- 'key' 'value' 'bad' \
-            2> /dev/null
+              2>&1 >/dev/null \
+            | assert::error_message "Failed to assign value 'value' to key 'key' in map 'MY_MAP'." \
+                "Expected a record with two or fewer fields, but got 'key value bad'."
         assert::failed
         set -e
     }
 
-    set_builtin
-    set_builtin_default
+    # set_escaping
+    # set_builtin
+    # set_builtin_default
 
-    set_indirect
-    set_indirect_default
+    # set_indirect
+    # set_indirect_default
 
     set_udt
 
-    test_bad_value
-    test_too_many_values
+    # test_bad_value
+    # test_too_many_values
+    # test_missing_field
 }
 
 cli::main "$@"
