cp

diff --git a/src/loader b/src/loader
--- a/src/loader
+++ b/src/loader
@@ -17,52 +17,15 @@ Global Arguments
 EOF
 }
 
-cli::loader::cache::load() {
-    declare -g CLI_LOADER_SOURCE_PATH="$1"
-    declare -g CLI_LOADER_SOURCE_NAME="${CLI_LOADER_SOURCE_PATH##*/}"
-    declare -g CLI_LOADER_SOURCE_DIR="${CLI_LOADER_SOURCE_PATH%/*}"
-    declare -g CLI_LOADER_CACHE_DIR="${CLI_LOADER_SOURCE_DIR}/.cli/${CLI_LOADER_SOURCE_NAME}"
+set -e
+set -u 
+set -o pipefail
+shopt -s lastpipe
 
-    declare -g CLI_LOADER_GROUP_IMPORT=". .group"
-    declare -g CLI_LOADER_GROUP_IMPORT_PATH="${CLI_LOADER_SOURCE_DIR}/.group"
-    declare -g CLI_LOADER_PARENT_GROUP_IMPORT=".. .group"
-    declare -g CLI_LOADER_PARENT_GROUP_IMPORT_PATH="${CLI_LOADER_SOURCE_DIR}/../.group"
+declare CLI_LOADER_DIR="${BASH_SOURCE%/*}"
 
-    declare -g CLI_LOADER_INITIALIZE_PATH="${CLI_LOADER_CACHE_DIR}/initialize.sh"
-    declare -g CLI_LOADER_BINDINGS_PATH="${CLI_LOADER_CACHE_DIR}/bindings.sh"
-    declare -g CLI_LOADER_IMPORTS_SOURCE_PATH="${CLI_LOADER_CACHE_DIR}/imports.sh"
-    declare -g CLI_LOADER_EXPORTS_PATH="${CLI_LOADER_CACHE_DIR}/exports.sh"
-
-    if [[ ! -d "${CLI_LOADER_CACHE_DIR}" ]]; then
-        mkdir -p "${CLI_LOADER_CACHE_DIR}"
-    fi
-}
-
-cli::loader::cache::test() {
-    if [[ -n "${CLI_LOADER_DISABLE_CACHE-}" ]]; then
-        false
-        return
-    fi
-
-    local cache="$1"
-    local expiration="${CLI_LOADER_SOURCE_PATH}"
-
-    if [[ ! -f "${cache}"  ]] || [[ "${cache}" -ot "${expiration}" ]]; then
-        false
-    else
-        true
-    fi
-}
-
-cli::loader::dry_run() {
-    if [[ "${arg_dry_run:-}" == "true" ]]; then 
-        # removes extra spaces which is typically what we want
-        while read; do echo ${REPLY}; done
-    else
-        if [[ "${arg_debug:-}" == "true" ]]; then set -x; fi
-        source /dev/stdin
-        if [[ "${arg_debug:-}" == "true" ]]; then set +x; fi
-    fi
+cli::loader::is_declared() {
+    if declare -F "$1" > /dev/null; then true; else false; fi
 }
 
 cli::loader::escape_args_then_call_as() {
@@ -77,15 +40,50 @@ cli::loader::escape_args_then_call_as() {
     sudo su "${user}" -c "${args[*]}"
 }
 
-cli::loader::cache::put() {
-    local path="$1"
-    local temp_path=$(mktemp "$1.XXXXXX")
-    
-    while read -r; do
-        echo "${REPLY}" >> "$temp_path"
-    done
+cli::loader::dry_run() {
+    if [[ "${arg_dry_run:-}" == "true" ]]; then 
+        # removes extra spaces which is typically what we want
+        while read; do echo ${REPLY}; done
+    else
+        if [[ "${arg_debug:-}" == "true" ]]; then set -x; fi
+        source /dev/stdin
+        if [[ "${arg_debug:-}" == "true" ]]; then set +x; fi
+    fi
+}
 
-    mv "$temp_path" "$path"
+cli::loader::cache::load() {
+    declare -g CLI_LOADER_SOURCE_PATH="$1"
+    declare -g CLI_LOADER_SOURCE_NAME="${CLI_LOADER_SOURCE_PATH##*/}"
+    declare -g CLI_LOADER_SOURCE_DIR="${CLI_LOADER_SOURCE_PATH%/*}"
+    declare -g CLI_LOADER_CACHE_DIR="${CLI_LOADER_SOURCE_DIR}/.cli/${CLI_LOADER_SOURCE_NAME}"
+
+    declare -g CLI_LOADER_INITIALIZE_PATH="${CLI_LOADER_CACHE_DIR}/initialize.sh"
+    declare -g CLI_LOADER_BINDINGS_PATH="${CLI_LOADER_CACHE_DIR}/bindings.sh"
+    declare -g CLI_LOADER_IMPORTS_SOURCE_PATH="${CLI_LOADER_CACHE_DIR}/imports.sh"
+    declare -g CLI_LOADER_EXPORTS_PATH="${CLI_LOADER_CACHE_DIR}/exports.sh"
+
+    if [[ ! -d "${CLI_LOADER_CACHE_DIR}" ]]; then
+        mkdir -p "${CLI_LOADER_CACHE_DIR}"
+    fi
+}
+
+cli::import() {
+    CLI_LOADER_IMPORTS+=( "$*" )
+}
+
+cli::import_group() {
+    cli::import ${CLI_DIR} .group
+}
+
+cli::loader::cache::put() {
+    arg_cache="$1" \
+        ::cli::cache::put::inline
+}
+
+cli::loader::cache::test() {
+    arg_cache="$1" \
+    arg_source="${CLI_LOADER_SOURCE_PATH}" \
+        ::cli::cache::test::inline
 }
 
 cli::loader::cache::exports() {
@@ -116,17 +114,26 @@ cli::loader::cache::initialize() {
     fi
 }
 
-cli::import() {
-    CLI_LOADER_IMPORTS+=( "$*" )
-}
+cli::loader::cache::test::bindings() {
+    local cached=true
+    local path=
 
-cli::loader::resolve() {
-    if [[ "$1" == '.' ]]; then
-        shift
-        cli callsite '--base' "${CLI_LOADER_SOURCE_DIR}" '--' "$@"
-    else
-        $@ '---which'
-    fi
+    # deserialize bindings
+    source "${CLI_LOADER_BINDINGS_PATH}"
+
+    for import in "${!bindings[@]}"; do
+        path=${bindings["$import"]}
+
+        # if an import is newer than the cache, then the cache is stale OR
+        # if an import does not resolve to the cached path, then the cache is stale
+        if [[ "${path}" -nt "${CLI_LOADER_BINDINGS_PATH}" ]] ||
+            [[ ! "$(${import} ---which)" == "${path}" ]]; then
+            cached=false
+            break
+        fi
+    done
+
+    ${cached}
 }
 
 cli::loader::cache::bindings() {
@@ -134,22 +141,20 @@ cli::loader::cache::bindings() {
     local import
     local path
 
-    # echo ${CLI_LOADER_BINDINGS_PATH} > /dev/stderr
     while [[ -n ${CLI_LOADER_IMPORTS[@]} ]]; do
         import="${CLI_LOADER_IMPORTS[0]}"
 
         # capture the mappting from import to path
-        path=$(cli::loader::resolve ${import})
+        path=$(${import} '---which')
         bindings+=( [${import}]="${path}" )
 
         # capture transitivie imports by executing 
         # the source generated by the import
-        source /dev/stdin < <(${path} ---exports)
+        ${path} ---exports \
+            | source /dev/stdin
 
         # pop this import
         CLI_LOADER_IMPORTS=( "${CLI_LOADER_IMPORTS[@]:1}" )
-
-    # pipe the list of imports into a file
     done 
         
     # serialize mapping of imports to paths
@@ -159,7 +164,6 @@ cli::loader::cache::bindings() {
 cli::loader::cache::imports() {
     local import
     local path
-    local cached=false
     local -A bindings
 
     # if source has been refreshed since the cli was executed, the cache is ok
@@ -170,39 +174,17 @@ cli::loader::cache::imports() {
         fi
     fi
 
-    # check if the cache is stale
-    if cli::loader::cache::test "${CLI_LOADER_IMPORTS_SOURCE_PATH}"; then
-        cached=true
+    if cli::loader::cache::test "${CLI_LOADER_BINDINGS_PATH}" &&
+        cli::loader::cache::test::bindings; then
 
-        # deserialize bindings used to generate the import source
-        source "${CLI_LOADER_BINDINGS_PATH}"
-
-        for import in "${!bindings[@]}"; do
-            path=${bindings["$import"]}
-
-            # echo "${CLI_LOADER_IMPORTS_SOURCE_PATH}, $path, $import" > /dev/stderr
-
-            # if an import is newer than the cache, then the cache is stale OR
-            # if an import does not resolve to the cached path, then the cache is stale
-            # if [[ "${path}" -nt "${CLI_LOADER_BINDINGS_PATH}" ]] || \
-            #     [[ ! "$(${import} ---which)" == "${path}" ]]; then
-            if [[ "${path}" -nt "${CLI_LOADER_BINDINGS_PATH}" ]]; then
-           
-                # echo "${path}" -nt "${CLI_LOADER_BINDINGS_PATH}" > /dev/stderr
-                
-                cached=false
-                break
-            fi
-        done
-    fi
-
-    if ${cached}; then 
+        touch "${CLI_LOADER_BINDINGS_PATH}"
         touch "${CLI_LOADER_IMPORTS_SOURCE_PATH}"
         return
     fi
 
-    # read cached bindings between inports and paths
-    source /dev/stdin < <(cli::loader::cache::bindings)
+    # generate and read cached bindings (e.g. map from inports to paths)
+    cli::loader::cache::bindings \
+        | source /dev/stdin
 
     for import in "${!bindings[@]}"; do
         path="${bindings["${import}"]}"
@@ -272,30 +254,22 @@ cli::loader::self_test() {
     exit ${result}
 }
 
-cli::loader::is_declared() {
-    if declare -F "$1" > /dev/null; then true; else false; fi
-}
-
 cli::load() {
 
-    # if there is a '.group' command and...
-    if [[ ! "${CLI_LOADER_SOURCE_NAME}" == '.group' ]] && \
-        # ...this command is not '.group', then...
-        [[ -f "${CLI_LOADER_GROUP_IMPORT_PATH}" ]]; then
-
-        # import '. .group'
-        CLI_LOADER_IMPORTS+=('. .group')
-    fi
-
-    # add implicit 'export' and 'initialize' imports
-    if cli::loader::is_declared export; then
+     if cli::loader::is_declared export; then
         CLI_LOADER_IMPORTS+=( \
-            'cli export' \
-            'cli initialize' \
+            'cli emit export' \
+            'cli emit initialize' \
         )
     fi
 
     case "${1-}" in
+        '---inline')
+            cli emit inline \
+                --name "$(cli path join --delimiter '::' -- ${CLI_PATH})::inline" \
+                --path "${CLI_LOADER_SOURCE_PATH}"
+            exit
+            ;;
         '---which') 
             echo "${CLI_LOADER_SOURCE_PATH}"
             exit
@@ -306,7 +280,8 @@ cli::load() {
             ;;
         '---imports')
             cli::loader::cache::imports
-            cat "${CLI_LOADER_BINDINGS_PATH}"
+            source "${CLI_LOADER_BINDINGS_PATH}"
+            for i in "${!bindings[@]}"; do echo "${i} -> ${bindings[$i]}"; done
             exit
             ;;
         '---initialize')
@@ -352,7 +327,7 @@ main() {
 
     echo 'set -e'
     echo 'set -u' 
-    # set -o pipefail
+    echo 'set -o pipefail'
     echo
 
     # run the last segment of a pipeline in the current execution process, not a subshell.
@@ -380,9 +355,9 @@ main() {
     echo "declare -a CLI_LOADER_IMPORTS"
 
     declare -f cli::import
+    declare -f cli::import_group
     declare -f cli::load
 
-    declare -f cli::loader::resolve
     declare -f cli::loader::dry_run
     declare -f cli::loader::escape_args_then_call_as
     declare -f cli::loader::execute
@@ -413,16 +388,22 @@ main() {
 
         declare -f cli
     else
-        declare -f cli::loader::is_declared
-        declare -f cli::loader::cache::load
+
         declare -f cli::loader::cache::test
         declare -f cli::loader::cache::put
+
+        declare -f cli::loader::is_declared
+        declare -f cli::loader::cache::load
+        declare -f cli::loader::cache::test::bindings
         declare -f cli::loader::cache::initialize
         declare -f cli::loader::cache::imports
         declare -f cli::loader::cache::exports
         declare -f cli::loader::cache::bindings
         declare -f cli::loader::source::imports
         declare -f cli::loader::source::initialize
+
+        declare -f ::cli::cache::put::inline
+        declare -f ::cli::cache::test::inline
 
         echo
         echo "cli::loader::cache::load \"\${BASH_SOURCE[1]}\""
@@ -447,10 +428,36 @@ initialize() {
     done
 }
 
-set -e
-set -u 
 declare -a CLI_LOADER_IMPORTS
 cli::loader::cache::load ${BASH_SOURCE}
+
+cat "${BASH_SOURCE%/*}/emit/inline" \
+    | {
+        while true; do
+            read -r
+            if [[ "${REPLY}" == 'main() {' ]]; then
+                echo "::cli::inline::inline() {"
+                while true; do 
+                    read -r
+                    echo "${REPLY}"
+                    if [[ ${REPLY} == '}' ]]; then
+                        exit
+                    fi
+                done
+            fi
+        done
+    } \
+    | source /dev/stdin
+        
+inline() {
+    arg_name="::cli::$1::inline" \
+    arg_path="${CLI_LOADER_DIR}/$2" \
+        ::cli::inline::inline \
+        | source /dev/stdin
+}
+
+inline 'cache::put' 'cache/put'
+inline 'cache::test' 'cache/test'
 
 if (( $# == 0 )); then
     if ! cli::loader::cache::test "${CLI_LOADER_EXPORTS_PATH}"; then
diff --git a/src/shim b/src/shim
--- a/src/shim
+++ b/src/shim
@@ -40,30 +40,6 @@ Examples
 EOF
 }
 
-cli::shim::help() {
-    cat << EOF
-Command
-    $1
-
-Summary
-    List available commands and groups.
-    
-Description
-    Operations on a group of commands include listing sub-groups,
-    commands, and both.
-
-Arguments
-    --list -l               : List commands and groups.
-    --commands -c           : List commands.
-    --groups -g             : List command groups.
-
-Global Arguments
-    --help -h        [Flag] : Show this message and exit.
-EOF
-}
-
-# support [Params], unify paths + function names + library_name, support relative paths
-
 # copied from 'loader'
 set +m
 set -e
@@ -73,16 +49,84 @@ shopt -s globstar
 shopt -s extglob
 shopt -s nullglob
 
-cli::shim::main() { 
-    local CLI_SHIM_ARG_GLOB="-*"
-    local CLI_SHIM_PATH_SEGMENT_GLOB="?([.])+([a-zA-Z0-9-])"
+# inline 'cli path join' and 'cli positional'
+declare CLI_SHIM_SOURCE_PATH="${BASH_SOURCE}"
+declare CLI_SHIM_SOURCE_NAME="${CLI_SHIM_SOURCE_PATH##*/}"
+declare CLI_SHIM_SOURCE_DIR="${CLI_SHIM_SOURCE_PATH%/*}"
+declare CLI_SHIM_CACHE_DIR="${CLI_SHIM_SOURCE_DIR}/.cli/${CLI_SHIM_SOURCE_NAME}"
+declare CLI_SHIM_CACHE_INLINE_PATH="${CLI_SHIM_CACHE_DIR}/inline.sh"
 
-    local path=
-    local callsite=
+# test cache
+if [[ ! -f "${CLI_SHIM_CACHE_INLINE_PATH}" ]] \
+    || [[ "${CLI_SHIM_CACHE_INLINE_PATH}" -ot "${CLI_SHIM_SOURCE_PATH}" ]]; then
 
-    callsite=$(cli::shim::callsite "$@")
-    eval "set ${callsite}"
-    path=$1; shift
+    declare CLI_SHIM_CACHE_INLINE_TEMP_PATH=$(mktemp "/tmp/cache.XXXXXX")
+
+    # ::cli::inline::inline
+    cat "${BASH_SOURCE%/*}/emit/inline" \
+        | {
+            while true; do
+                read -r
+                if [[ "${REPLY}" == 'main() {' ]]; then
+                    echo "::cli::inline::inline() {"
+                    while true; do 
+                        read -r
+                        echo "${REPLY}"
+                        if [[ ${REPLY} == '}' ]]; then
+                            exit
+                        fi
+                    done
+                fi
+            done
+        } \
+        | source /dev/stdin
+
+    # constants
+    inline() {
+        arg_name="::cli::$1::inline" \
+        arg_path="${CLI_SHIM_SOURCE_DIR}/$2" \
+            ::cli::inline::inline \
+            >> "${CLI_SHIM_CACHE_INLINE_TEMP_PATH}"
+    }
+
+    # cli/path/join -> ::cli::path::join::inline
+    inline "path::join" "path/join"
+
+    # cli/positional -> ::cli::positional::inline
+    inline "positional" "positional"
+
+    # create cache dir            
+    if [[ ! -d "${CLI_SHIM_CACHE_DIR}" ]]; then
+        mkdir -p "${CLI_SHIM_CACHE_DIR}"
+    fi
+
+    # put cache file
+    mv "${CLI_SHIM_CACHE_INLINE_TEMP_PATH}" "${CLI_SHIM_CACHE_INLINE_PATH}"
+fi
+
+# source inlined functions
+source "${CLI_SHIM_CACHE_INLINE_PATH}"
+
+cli::shim::is_command() { test -f "$1" && test -x "$1"; }
+cli::shim::is_group() { test -d "$1" && test -x "$1"; }
+cli::shim::list() { cli list --dir "$1"; }
+
+cli::shim::cache::start_time() {
+    if ! declare -p CLI_LOADER_IMPORTS_EXPIRATION_PATH >/dev/null 2>&1; then
+        declare -xg CLI_LOADER_IMPORTS_EXPIRATION_PATH="$(mktemp "/tmp/cli.XXXXXX")"
+        cli::shim::on_exit() { 
+            rm "${CLI_LOADER_IMPORTS_EXPIRATION_PATH}"
+        }
+        trap cli::shim::on_exit EXIT
+    fi
+}
+
+main() {
+    local positional_arg_count=$(::cli::positional::inline "$@")
+    local positional_args=( "${@:1:${positional_arg_count}}" )
+    local optional_args=( "${@:$(( positional_arg_count + 1 ))}" )
+    local cli_path=( "${arg_name}" "${positional_args[@]}" )
+    local path=$(arg_delimiter='/' ::cli::path::join::inline "${positional_args[@]}")
 
     # file
     if cli::shim::is_command "${path}"; then
@@ -92,11 +136,13 @@ cli::shim::main() {
             '---which')
                 echo "${path}" ;; 
             *)
-                if ! declare -p CLI_LOADER_IMPORTS_EXPIRATION_PATH >/dev/null 2>&1; then
-                    declare -xg CLI_LOADER_IMPORTS_EXPIRATION_PATH="$(mktemp "/tmp/cli.XXXXXX")"
-                    trap cli::shim::on_exit EXIT
-                fi
-                "${path}" "$@"
+                cli::shim::cache::start_time
+                
+                declare -x CLI_PATH="${cli_path[@]}"
+                declare -x CLI_NAME="${cli_path[@]: -1:1}"
+                declare -x CLI_DIR="${cli_path[@]:0:$(( positional_arg_count ))}"
+
+                "${path}" "${optional_args[@]}"
                 ;;
 
         esac
@@ -107,109 +153,17 @@ cli::shim::main() {
 
     # fail
     else
-        cli::shim::command_not_found "${path#${dir}}"
+        echo "Command \"${path}\" not found."
+        exit 1
     fi
 }
-
-# copied from callsite
-cli::shim::callsite() {
-    declare CLI_CALL_ARG_GLOB="-*"
-    declare CLI_CALL_PATH_SEGMENT_GLOB="?([.])+([a-zA-Z0-9-])"
-
-    # use filesystem to resolve command, and first argument is the 
-    # base directory where commands are under development
-    local delimiter=
-    local dir=
-    local path=
-
-    # shift path root
-    dir=${arg_base}
-    path="${dir}"
-
-    # pick a path dilimiter
-    delimiter='/'
-    if [[ "${arg_type}" == 'function' ]]; then
-        delimiter='::'
-    fi
-
-    # compose command path by consuming args upto first dash argument 
-    while (( $# > 0 )); do
-
-        # stop joining path segments if an argument is found (e.g. --foo)
-        if [[ "$1" == $CLI_CALL_ARG_GLOB ]]; then 
-            break
-        fi
-
-        # ensure uniformity of group names (e.g. foo-bar, not foo_bar)
-        if [[ ! "$1" == $CLI_CALL_PATH_SEGMENT_GLOB ]]; then
-            echo "Unexpected command name or group '$1' does not match '$CLI_CALL_PATH_SEGMENT_GLOB'."
-            exit 1
-        fi
-
-        # if path does not end in a delimiter, then add one (e.g. '::' or '/')
-        if [[ -n "${path}" && ! "${path}" =~ .*${delimiter}$ ]]; then
-            path="${path}${delimiter}"
-        fi
-
-        # convert command or group name into file or function name (e.g. foo-bar -> foo_bar)
-        path="${path}${1//-/_}"
-        shift
-    done
-
-    printf '%q' "${path}"
-    for i in "$@"; do
-        printf ' %q' "${i}"
-    done
-    echo
-}
-
-cli::shim::on_exit() {
-    rm "${CLI_LOADER_IMPORTS_EXPIRATION_PATH}"
-}
-
-cli::shim::is_command() {
-    local path="$1"
-    test -f "${path}" && test -x "${path}"
-}
-
-cli::shim::is_group() {
-    local path="$1"
-    test -d "${path}" && test -x "${path}"
-}
-
-cli::shim::list() (
-    cli list --dir "$1"
-)
-
-cli::shim::split() {
-    set "${1//${delimiter}/ }"  # replace '::' or '/' with space
-    set "${1//_/-}"             # replace '_' with '-'
-    echo $1
-}
-
-cli::shim::command_not_found() {
-    echo "Command '$(cli::shim::split $1)' not found."
-    exit 1
-}
-
-main() {
-    declare -f cli::shim::main
-    declare -f cli::shim::split
-    declare -f cli::shim::command_not_found
-
-    # these functions generated during packing
-    # declare -f cli::shim::is_command
-    # declare -f cli::shim::is_group
-    # declare -f cli::shim::list
-    # declare -g cli::shim::callsite
-}
-
 
 initialize() {
     
     # declarations
     declare -g arg_help=""
     declare -g arg_base=""
+    declare -g arg_name=""
     declare -g arg_type=""
     declare -g arg_self_test=""
     declare -g arg_help=""
@@ -225,6 +179,7 @@ initialize() {
     while (( $# > 0 )); do
         case "$1" in
             '--help') arg__[arg_help]="true"; arg_help=true ;;
+            '--name') arg__[arg_name]="${2:-}"; arg_name="${2:-}"; shift ;;
             '--base') arg__[arg_base]="${2:-}"; arg_base="${2:-}"; shift ;;
             '--type') arg__[arg_type]="${2:-}"; arg_type="${2:-}"; shift ;;
             '--self-test') arg__[arg_self_test]="true"; arg_self_test=true ;;
@@ -249,62 +204,19 @@ initialize() {
     esac
 }
 
-# echo "$@" > /dev/stderr
+# emulate loader
 case ${1-} in
-    '') main ;;
-    '-h') ;& '--help') help ;;
-    '--self-test') ;;
     '---print') cat ${BASH_SOURCE} ;;
     '---which') echo ${BASH_SOURCE} ;;
     '---exports') main ;;
     '---initialize') ;;
     '---imports') ;;
-    # -*) cli::shim::unexpected_argument "$1" ;;
     *) 
         initialize "$@"
-        if (( ${#arg_[0]} > 0)); then set "${arg_[@]}"; fi
-        cli::shim::main "$@" 
+
+        if ${arg_help}; then help; exit; fi
+        if ${arg_self_test}; then exit; fi
+
+        main "${arg_[@]}" 
     ;;
 esac
-
-# trash
-cli::shim::callsite::hide() (
-    local this_path="${BASH_SOURCE}"
-    local this_dir="${this_path%/*}"
-
-    # resolve well-known callsites (prevents inifinite recursion)
-    local loader="${this_dir}/loader"
-    if [[ "${arg_base}/$@" -ef "${loader}" ]]; then
-        echo "${loader}"
-        return
-    fi
-
-    set -- '--base' "${arg_base}" '--' "$@"
-
-    source "${this_dir}/callsite"
-)
-cli::shim::callsite::hide() {
-    local this_path="${BASH_SOURCE}"
-    local this_dir="${this_path%/*}"
-
-    # resolve well-known callsites (prevents inifinite recursion)
-    local loader="${this_dir}/loader"
-    if [[ "${arg_base}/$@" -ef "${loader}" ]]; then
-        echo "${loader}"
-        return
-    fi
-
-    local shim="${this_dir}/shim"
-    if [[ "${arg_base}/$1" -ef "${shim}" ]]; then
-        shift
-        echo "${shim} $@"
-        return
-    fi
-
-    # echo ${callsite} '--base' "${arg_base}" '--' "$@" > /dev/stderr
-    # ${callsite} '--base' "${arg_base}" '--' "$@" > /dev/stderr
-    # echo '---' > /dev/stderr
-
-    local callsite="${this_dir}/callsite"
-    ${callsite} '--base' "${arg_base}" '--' "$@"
-}
