cp

diff --git a/src/loader b/src/loader
--- a/src/loader
+++ b/src/loader
@@ -55,16 +55,14 @@ cli::loader::cache::load() {
     declare -g CLI_LOADER_SOURCE_PATH="$1"
     declare -g CLI_LOADER_SOURCE_NAME="${CLI_LOADER_SOURCE_PATH##*/}"
     declare -g CLI_LOADER_SOURCE_DIR="${CLI_LOADER_SOURCE_PATH%/*}"
+    
     declare -g CLI_LOADER_CACHE_DIR="${CLI_LOADER_SOURCE_DIR}/.cli/${CLI_LOADER_SOURCE_NAME}"
-
-    declare -g CLI_LOADER_INITIALIZE_PATH="${CLI_LOADER_CACHE_DIR}/initialize.sh"
-    declare -g CLI_LOADER_BINDINGS_PATH="${CLI_LOADER_CACHE_DIR}/bindings.sh"
-    declare -g CLI_LOADER_IMPORTS_SOURCE_PATH="${CLI_LOADER_CACHE_DIR}/imports.sh"
-    declare -g CLI_LOADER_EXPORTS_PATH="${CLI_LOADER_CACHE_DIR}/exports.sh"
-
     if [[ ! -d "${CLI_LOADER_CACHE_DIR}" ]]; then
         mkdir -p "${CLI_LOADER_CACHE_DIR}"
     fi
+
+    declare -g CLI_LOADER_INITIALIZE_PATH="${CLI_LOADER_CACHE_DIR}/initialize.sh"
+    declare -g CLI_LOADER_EXPORTS_PATH="${CLI_LOADER_CACHE_DIR}/exports.sh"
 }
 
 cli::import() {
@@ -75,116 +73,27 @@ cli::import_group() {
     cli::import ${CLI_GROUP} .group
 }
 
-cli::loader::cache::put() {
+cli::cache::put() {
     arg_cache="$1" \
         ::cli::cache::put::inline
 }
 
-cli::loader::cache::test() {
+cli::cache::test() {
     arg_cache="$1" \
     arg_source="${CLI_LOADER_SOURCE_PATH}" \
         ::cli::cache::test::inline
 }
 
-cli::loader::cache::test::bindings() {
-    local cached=true
-    local path=
-
-    # deserialize bindings
-    source "${CLI_LOADER_BINDINGS_PATH}"
-
-    for import in "${!bindings[@]}"; do
-        path=${bindings["$import"]}
-
-        # if an import is newer than the cache, then the cache is stale OR
-        # if an import does not resolve to the cached path, then the cache is stale
-        if [[ "${path}" -nt "${CLI_LOADER_BINDINGS_PATH}" ]] ||
-            [[ ! "$(${import} ---which)" == "${path}" ]]; then
-            cached=false
-            break
-        fi
-    done
-
-    ${cached}
-}
-
-cli::loader::cache::bindings() {
-    local -A bindings=()
-    local import
-    local path
-
-    while [[ -n ${CLI_LOADER_IMPORTS[@]} ]]; do
-        import="${CLI_LOADER_IMPORTS[0]}"
-
-        # capture the mappting from import to path
-        path=$(${import} '---which')
-        bindings+=( [${import}]="${path}" )
-
-        # capture transitivie imports by executing 
-        # the source generated by the import
-        ${path} ---exports \
-            | source /dev/stdin
-
-        # pop this import
-        CLI_LOADER_IMPORTS=( "${CLI_LOADER_IMPORTS[@]:1}" )
-    done 
-        
-    # serialize mapping of imports to paths
-    declare -p bindings
-}
-
-cli::loader::cache::imports() {
-    local import
-    local path
-    local -A bindings
-
-    # if source has been refreshed since the cli was executed, the cache is ok
-    if declare -p CLI_LOADER_IMPORTS_EXPIRATION_PATH >/dev/null 2>&1; then
-        if [[ "${CLI_LOADER_IMPORTS_EXPIRATION_PATH}" -ot \
-              "${CLI_LOADER_IMPORTS_SOURCE_PATH}" ]]; then
-              return
-        fi
-    fi
-
-    if cli::loader::cache::test "${CLI_LOADER_BINDINGS_PATH}" &&
-        cli::loader::cache::test::bindings; then
-
-        touch "${CLI_LOADER_BINDINGS_PATH}"
-        touch "${CLI_LOADER_IMPORTS_SOURCE_PATH}"
-        return
-    fi
-
-    # generate and read cached bindings (e.g. map from inports to paths)
-    cli::loader::cache::bindings \
-        | source /dev/stdin
-
-    for import in "${!bindings[@]}"; do
-        path="${bindings["${import}"]}"
-
-        # emit library
-        echo \#
-        echo \# ${import} '->' "${path}"
-        echo \#
-        ${path}
-        echo
-    done \
-        | cli::loader::cache::put "${CLI_LOADER_IMPORTS_SOURCE_PATH}"
-
-    # cache the bindings *after* updating the imports to prevent 
-    # a race between checking the cache and updating the cache
-    declare -p bindings > "${CLI_LOADER_BINDINGS_PATH}"
-}
-
 cli::loader::cache::exports() {
-    if ! cli::loader::cache::test "${CLI_LOADER_EXPORTS_PATH}"; then
-        "$0" | cli::loader::cache::put "${CLI_LOADER_EXPORTS_PATH}"
+    if ! cli::cache::test "${CLI_LOADER_EXPORTS_PATH}"; then
+        "$0" | cli::cache::put "${CLI_LOADER_EXPORTS_PATH}"
     fi
 }
 
 cli::loader::cache::initialize() {
 
     # test initialize cache 
-    if ! cli::loader::cache::test "${CLI_LOADER_INITIALIZE_PATH}"; then
+    if ! cli::cache::test "${CLI_LOADER_INITIALIZE_PATH}"; then
    
         # initialize hard coded
         if cli::loader::is_declared initialize; then
@@ -200,17 +109,59 @@ cli::loader::cache::initialize() {
                 | cli dsl tokenize \
                 | cli dsl parse \
                 | cli dsl emit \
-                | cli::loader::cache::put "${CLI_LOADER_INITIALIZE_PATH}"
+                | cli::cache::put "${CLI_LOADER_INITIALIZE_PATH}"
         fi
     fi
 }
 
-cli::loader::source::imports() {
-    cli::loader::cache::imports
-    source "${CLI_LOADER_IMPORTS_SOURCE_PATH}"
+cli::loader::load::imports() {
+    local command_path=
+    local cache_path=
+    local -a import=()
+    local -A imported=()
+    local -A base_path=()
+
+    # foreach import
+    for (( i=0; i < ${#CLI_LOADER_IMPORTS[@]}; i++ )); do
+        # verify import
+        # TODO
+
+        import=( ${CLI_LOADER_IMPORTS[i]} )
+
+        # if import previously seen, continue
+        if ${imported[${import[@]}]-false}; then
+            continue
+        fi
+        imported[${import[@]}]=true
+
+        # if base path not resolved
+        if [[ -z "${base_path[$import]-}" ]]; then
+
+            # resolve base path
+            base_path[${import}]=$(${import} '---which')
+            # if cli still not resolved, fail
+            # TODO
+        fi
+
+        # if import codegen cache stale
+        command_path=$(arg_delimiter='/' arg_base=${base_path[${import}]} \
+            ::cli::path::join::inline "${import[@]:1}")
+        cache_path="$(arg_path=${command_path} \
+            ::cli::cache::path::inline)/exports.sh"
+
+        if ! arg_cache="${cache_path}" arg_source="${command_path}" \
+            ::cli::cache::test::inline; then
+
+            # refresh import codegen cache
+            ${import[@]} '---exports' > /dev/null
+        fi
+            
+        # source codegen
+        source "${cache_path}"
+    done
 }
 
-cli::loader::source::initialize() {
+cli::loader::load::initialize() {
     cli::loader::cache::initialize
     source "${CLI_LOADER_INITIALIZE_PATH}"
 }
@@ -257,15 +208,6 @@ cli::loader::self_test() {
 }
 
 cli::load() {
-    # declare CLI_PATH, CLI_NAME, CLI_GROUP
-    : ${CLI_PATH:=${BASH_SOURCE[1]##*/}}
-    local path=( ${CLI_PATH} )
-    local length=${#path[@]}
-    declare -x CLI_NAME="${path[@]: -1:1}"
-    declare -x CLI_GROUP="${path[@]:0:$(( length - 1 ))}"
-    declare -x CLI_PARENT_GROUP="${path[@]:0:$(( length - 2 ))}"
-    unset path length
-
     # implicit imports
     if cli::loader::is_declared export; then
         CLI_LOADER_IMPORTS+=( \
@@ -300,19 +242,19 @@ cli::load() {
             exit
             ;;
         '---initialize')
-            cli::loader::source::imports
+            cli::loader::load::imports
             cli::loader::cache::initialize
-            cat "${CLI_LOADER_INITIALIZE_PATH}"
+            echo "${CLI_LOADER_INITIALIZE_PATH}"
             exit
             ;;
         '---exports')
             cli::loader::cache::exports
-            cat "${CLI_LOADER_EXPORTS_PATH}"
+            echo "${CLI_LOADER_EXPORTS_PATH}"
             exit
             ;;
     esac 
 
-    cli::loader::source::imports
+    cli::loader::load::imports
 
     for i in "$@"; do
         case "${i}" in
@@ -331,7 +273,7 @@ cli::load() {
         ;;
     esac 
 
-    cli::loader::source::initialize
+    cli::loader::load::initialize
     cli::loader::execute "$@"
 }
 
@@ -367,7 +309,14 @@ main() {
     echo "self_test() { return; }"
     echo
 
-    echo "declare -a CLI_LOADER_IMPORTS"
+    echo "declare -a CLI_LOADER_IMPORTS=()"
+    echo ": \${CLI_PATH:=\${BASH_SOURCE[1]##*/}}"
+    echo "declare path=( \${CLI_PATH} )"
+    echo "declare length=\${#path[@]}"
+    echo "declare CLI_NAME=\"\${path[@]: -1:1}\""
+    echo "declare CLI_GROUP=\"\${path[@]:0:\$(( length - 1 ))}\""
+    echo "declare CLI_PARENT_GROUP=\"\${path[@]:0:\$(( length - 2 ))}\""
+    echo "unset path length"
 
     declare -f cli::import
     declare -f cli::import_group
@@ -404,21 +353,20 @@ main() {
         declare -f cli
     else
 
-        declare -f cli::loader::cache::test
-        declare -f cli::loader::cache::put
+        declare -f ::cli::cache::put::inline
+        declare -f ::cli::cache::test::inline
+        declare -f ::cli::cache::path::inline
+        declare -f ::cli::path::join::inline
+
+        declare -f cli::cache::test
+        declare -f cli::cache::put
 
         declare -f cli::loader::is_declared
         declare -f cli::loader::cache::load
-        declare -f cli::loader::cache::test::bindings
         declare -f cli::loader::cache::initialize
-        declare -f cli::loader::cache::imports
         declare -f cli::loader::cache::exports
-        declare -f cli::loader::cache::bindings
-        declare -f cli::loader::source::imports
-        declare -f cli::loader::source::initialize
-
-        declare -f ::cli::cache::put::inline
-        declare -f ::cli::cache::test::inline
+        declare -f cli::loader::load::imports
+        declare -f cli::loader::load::initialize
 
         echo
         echo "cli::loader::cache::load \"\${BASH_SOURCE[1]}\""
@@ -473,11 +421,13 @@ inline() {
 
 inline 'cache::put' 'cache/put'
 inline 'cache::test' 'cache/test'
+inline 'cache::path' 'cache/path'
+inline 'path::join' 'path/join'
 
 if (( $# == 0 )); then
-    if ! cli::loader::cache::test "${CLI_LOADER_EXPORTS_PATH}"; then
+    if ! cli::cache::test "${CLI_LOADER_EXPORTS_PATH}"; then
         : ${arg_pack:=false}
-        main | cli::loader::cache::put "${CLI_LOADER_EXPORTS_PATH}"
+        main | cli::cache::put "${CLI_LOADER_EXPORTS_PATH}"
     fi
     echo "${CLI_LOADER_EXPORTS_PATH}"
     exit
