cp

diff --git a/src/loader b/src/loader
--- a/src/loader
+++ b/src/loader
@@ -17,6 +17,12 @@ Global Arguments
 EOF
 }
 
+set -e
+set -u 
+set -o pipefail
+shopt -s lastpipe
+
+# cache
 declare BASH_DIR="${BASH_SOURCE%/*}"
 declare BASH_NAME="${BASH_SOURCE##*/}"
 declare CACHE_DIR="${BASH_DIR}/.cli/${BASH_NAME}"
@@ -27,18 +33,44 @@ if [[ -f "${EXPORTS_PATH}" ]] \
     exit
 fi
 
-set -e
-set -u 
-set -o pipefail
-shopt -s lastpipe
+declare -a CLI_LOADER_IMPORTS=()
+: ${CLI_COMMAND:=${BASH_SOURCE##*/}}
 
-cli::loader::cache::load() {
-    declare -g CLI_LOADER_COMMAND_PATH="$1"
-    declare -g CLI_LOADER_CACHE_DIR="$(arg_path="${CLI_LOADER_COMMAND_PATH}" \
-        ::cli::cache::path::inline)"
-    declare -g CLI_LOADER_INITIALIZE_PATH="${CLI_LOADER_CACHE_DIR}/initialize.sh"
-    declare -g CLI_LOADER_EXPORTS_PATH="${CLI_LOADER_CACHE_DIR}/exports.sh"
-    declare -g CLI_LOADER_METADATA_PATH="${CLI_LOADER_CACHE_DIR}/metadata.sh"
+cli::loader::import_inline() {
+    cat "${BASH_SOURCE%/*}/emit/inline" \
+        | {
+            while true; do
+                read -r
+                if [[ "${REPLY}" == 'inline() {' ]]; then
+                    echo "::cli::inline::inline() {"
+                    while true; do 
+                        read -r
+                        echo "${REPLY}"
+                        if [[ ${REPLY} == '}' ]]; then
+                            exit
+                        fi
+                    done
+                fi
+            done
+        } \
+        | source /dev/stdin
+            
+    inline() {
+        arg_name="::cli::$1::inline" \
+            ::cli::inline::inline < "${BASH_DIR}/$2" \
+            | source /dev/stdin
+    }
+
+    inline 'cache::put' 'cache/put'
+    inline 'cache::test' 'cache/test'
+    inline 'cache::path' 'cache/path'
+    inline 'path::join' 'path/join'
+    inline 'args::parse' 'args/parse'
+    inline 'args::tokenize' 'args/tokenize'
+    inline 'args::parse' 'args/parse'
+    inline 'reflection::is_function_declared' 'reflection/is_function_declared'
+    inline 'reflection::run_as' 'reflection/run_as'
+    inline 'util::fail' 'util/fail'
 }
 
 cli::fail() {
@@ -57,9 +89,17 @@ cli::import_group() {
     cli::import ${group} .group
 }
 
-cli::cache::put() {
-    arg_cache="$1" \
-        ::cli::cache::put::inline
+cli::import_inline() {
+    cli::import "$*"
+}
+
+cli::loader::cache::load() {
+    declare -g CLI_LOADER_COMMAND_PATH="$1"
+    declare -g CLI_LOADER_CACHE_DIR="$(arg_path="${CLI_LOADER_COMMAND_PATH}" \
+        ::cli::cache::path::inline)"
+    declare -g CLI_LOADER_INITIALIZE_PATH="${CLI_LOADER_CACHE_DIR}/initialize.sh"
+    declare -g CLI_LOADER_EXPORTS_PATH="${CLI_LOADER_CACHE_DIR}/exports.sh"
+    declare -g CLI_LOADER_METADATA_PATH="${CLI_LOADER_CACHE_DIR}/metadata.sh"
 }
 
 cli::cache::test() {
@@ -81,7 +121,9 @@ cli::loader::cache::exports() {
         # procedural; e.g library
         else
             "$0" 
-        fi | cli::cache::put "${CLI_LOADER_EXPORTS_PATH}"
+        fi \
+        | arg_cache="${CLI_LOADER_EXPORTS_PATH}" \
+            ::cli::cache::put::inline
     fi
 }
 
@@ -100,13 +142,15 @@ cli::loader::cache::initialize() {
             | cli dsl tokenize \
             | cli dsl parse \
             | cli dsl emit \
-            | cli::cache::put "${CLI_LOADER_INITIALIZE_PATH}"
+            | arg_cache="${CLI_LOADER_INITIALIZE_PATH}" \
+                ::cli::cache::put::inline
 
         "$0" '--help' \
             | cli dsl tokenize \
             | cli dsl parse \
             | cli dsl meta \
-            | cli::cache::put "${CLI_LOADER_METADATA_PATH}"
+            | arg_cache="${CLI_LOADER_METADATA_PATH}" \
+                ::cli::cache::put::inline
     fi
 }
 
@@ -148,7 +192,8 @@ cli::loader::load::imports() {
             ::cli::cache::path::inline)/exports.sh"
 
         # if import codegen cache stale
-        if ! arg_cache="${exports_path}" arg_source="${import_path}" \
+        if ! arg_cache="${exports_path}" \
+            arg_source="${import_path}" \
             ::cli::cache::test::inline; then
 
             # refresh import codegen cache
@@ -338,6 +383,7 @@ main() {
     declare -f cli::fail
     declare -f cli::import
     declare -f cli::import_group
+    declare -f cli::import_inline
     declare -f cli::load
     echo
 
@@ -345,17 +391,18 @@ main() {
     declare -f cli::loader::self_test
     echo
 
-    declare -f ::cli::cache::put::inline
     declare -f ::cli::cache::test::inline
     declare -f ::cli::cache::path::inline
+    declare -f ::cli::cache::put::inline
     declare -f ::cli::path::join::inline
     declare -f ::cli::reflection::is_function_declared::inline
     declare -f ::cli::reflection::run_as::inline
     declare -f ::cli::util::fail::inline
+    declare -f ::cli::args::tokenize::inline
+    declare -f ::cli::args::parse::inline
     echo
 
     declare -f cli::cache::test
-    declare -f cli::cache::put
     echo
 
     if ${arg_pack}; then
@@ -387,6 +434,8 @@ main() {
         declare -f cli::loader::cache::load
         declare -f cli::loader::cache::initialize
         declare -f cli::loader::cache::exports
+        echo
+
         declare -f cli::loader::load::imports
         declare -f cli::loader::load::initialize
         echo
@@ -416,46 +465,14 @@ initialize() {
     done
 }
 
-declare -a CLI_LOADER_IMPORTS=()
-
-cat "${BASH_SOURCE%/*}/emit/inline" \
-    | {
-        while true; do
-            read -r
-            if [[ "${REPLY}" == 'inline() {' ]]; then
-                echo "::cli::inline::inline() {"
-                while true; do 
-                    read -r
-                    echo "${REPLY}"
-                    if [[ ${REPLY} == '}' ]]; then
-                        exit
-                    fi
-                done
-            fi
-        done
-    } \
-    | source /dev/stdin
-        
-inline() {
-    arg_name="::cli::$1::inline" \
-        ::cli::inline::inline < "${BASH_DIR}/$2" \
-        | source /dev/stdin
-}
-
-inline 'cache::put' 'cache/put'
-inline 'cache::test' 'cache/test'
-inline 'cache::path' 'cache/path'
-inline 'path::join' 'path/join'
-inline 'args::parse' 'args/parse'
-inline 'reflection::is_function_declared' 'reflection/is_function_declared'
-inline 'reflection::run_as' 'reflection/run_as'
-inline 'util::fail' 'util/fail'
-
+cli::loader::import_inline
 cli::loader::cache::load ${BASH_SOURCE}
 
+# refresh cache
 if (( $# == 0 )); then
     : ${arg_pack:=false}
-    main | cli::cache::put "${CLI_LOADER_EXPORTS_PATH}"
+    main | arg_cache="${CLI_LOADER_EXPORTS_PATH}" \
+        ::cli::cache::put::inline
     echo "${CLI_LOADER_EXPORTS_PATH}"
     exit
 fi
