cp

diff --git a/src/loader b/src/loader
--- a/src/loader
+++ b/src/loader
@@ -1,5 +1,4 @@
 #!/usr/bin/env bash
-# source /dev/stdin < <(cli loader)
 
 help() {
     cat << EOF
@@ -17,42 +16,6 @@ Global Arguments
     --help -h       : Show this message and exit.
     --self-test     : Runs a self test.
 EOF
-}
-
-cli::export_functions() {
-    local glob
-
-    for i in "$@"; do 
-        glob+="${i}::"
-    done
-
-    while read keyword flags name; do
-        if [[ "${name}" == ${glob}* ]]; then
-            declare -f "${name}"
-        fi
-    done < <(declare -F)
-}
-
-cli::export_variables() {
-    local -u glob
-
-    for i in "$@"; do 
-        glob+="${i}_"; 
-    done
-
-    for i in $(eval echo "\${!${glob}@}"); do
-        declare -p "${i}" \
-            | sed 's/^declare/declare -g/'
-    done
-}
-
-cli::export_import() {
-    echo "source /dev/stdin < <(cli::import $@)"
-}
-
-cli::export() {
-    cli::export_variables "$@"
-    cli::export_functions "$@"
 }
 
 cli::reference() {
@@ -106,42 +69,54 @@ cli::define_initialize() {
     fi
 }
 
-cli::initialize() {
-    : ${arg_help:=false}
-    : ${arg_self_test:=false}
-
-    while (( $# > 0 )); do
-        case $1 in
-            '-h') ;& '--help') arg_help=true ;;
-            '--self-test') arg_self_test=true ;;
-            *) echo "Unexpected argument $1."; exit 1 ;;
-        esac
-
-        shift
-    done
-}
-
 cli::load() {
-    cli::define_initialize "${FUNCNAME[1]}"
 
-    # implement well know feature flags
+    # dump help if '-h' or '--help' appear anywhere on the command line
     for i in "$@"; do
-
-        # dump help
         if [[ "${i}" == '-h' ]] || [[ "${i}" == '--help' ]]; then 
-            help; exit
-
-        # run self test
-        elif [[ "${i}" == '--self-test' ]]; then
-            self_test; exit
-
-        # emit initialize
-        elif [[ "${i}" == '---emit-initialize' ]]; then
-            declare -f initialize
+            help
             exit
         fi
     done
     unset i
+
+    case "${1-}" in
+
+        # run self test
+        '--self-test')
+            self_test
+            result=$?
+            if ! (( ${result} == 0 )); then
+                read line file < <(caller)
+                echo "Self-test failed: ${file}"
+            fi
+            exit ${result}
+        ;;
+
+        # test for custom initialize
+        '---test-initialize')
+            declare -F initialize > /dev/null
+            exit
+        ;;
+
+        # emit calling file (e.g. for packing)
+        '---emit')
+            caller | read line file
+            cat "$file"
+            exit 
+        ;;
+    esac 
+
+    cli::define_initialize "${FUNCNAME[1]}"
+
+    case "${1-}" in
+ 
+        # emit initialize
+        '---emit-initialize')
+            declare -f initialize
+            exit
+        ;;
+   esac 
 
     # declare well known variables
     : ${arg_run_as:=}
@@ -164,13 +139,11 @@ cli::load() {
 
 initialize() {
     : ${arg_help:=false}
-    : ${arg_library:=false}
     : ${arg_self_test:=false}
 
     while (( $# > 0 )); do
         case $1 in
             '-h') ;& '--help') arg_help=true ;;
-            '-l') ;& '--library') arg_library=true ;;
             '--self-test') arg_self_test=true ;;
             *) echo "Unexpected argument $1."; exit 1 ;;
         esac
@@ -215,17 +188,15 @@ main() {
     if [[ ${CLI_REFLECT:-} == 'true' ]]; then
         # prevent JIT to prevent capturing libraries used during JIT
         echo "initialize() { return; }"
-
-    elif ${arg_library}; then
-
-        # defining libraries as commands-with-a-common-initialize-function allows:
-        # 1. using PATH to resolve libraries which helps hide paths which aids packing
-        # 2. support packaging test in libraries and executing them via '--self-test'
-        # 3. support '.group' as a library that doubles as metadata via '-h' for the group
-        echo "initialize() { cli::initialize "\$@"; }"
     fi
-    
-    cli::export cli
+
+    declare -f cli::import
+    declare -f cli::reference
+    declare -f cli::dry_run
+    declare -f cli::escape_args_then_call_as
+    declare -f cli::define_initialize
+    declare -f cli::initialize
+    declare -f cli::load
 }
 
 cli::load "$@"
